runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /api/.*
  script: api.app
- url: /entry/
  static_files: frontend/entry/index.html
  upload: frontend/entry/index.html
- url: /entry/(.*)
  static_files: frontend/entry/\1
  upload: frontend/entry/.*
- url: .*
  script: main.app
