runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /api/.*
  script: api.app
- url: /routing/.*
  script: routing_service.app
- url: /train/.*
  script: railway_api_integrator.app
- url: /entry/
  static_files: frontend/entry/index.html
  upload: frontend/entry/index.html
- url: /entry/(.*)
  static_files: frontend/entry/\1
  upload: frontend/entry/.*
- url: /(test|control)
  script: main.app
- url: /
  static_files: frontend/web/index.html
  upload: frontend/web/index.html
- url: /(.*)
  static_files: frontend/web/\1
  upload: frontend/web/.*
